# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05405a1487d905733db2a31a133c0a0b1474866708d13fe01082f61afd295ca1f040acc9300813557c194d6649cf0dd32288f300c3a60d8395c7a512836ed40e

test:
  secret_key_base: 5298da5643e1a8bebfa900792e2d3ee5494a4239df6875c64b86cb2cf4e9882721c6494bfc8a843088014b6cc30844298c44b0a874eff8567765313e2a7badc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
